# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhifangtu.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1172, 746)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_10 = QtWidgets.QWidget(Form)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.widget_10)
        self.frame_2.setMinimumSize(QtCore.QSize(351, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(351, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.toolBox = QtWidgets.QToolBox(self.frame_2)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 329, 610))
        self.page.setObjectName("page")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 51, 21))
        self.label_7.setObjectName("label_7")
        self.zft_yw_hzzft_pushButton = QtWidgets.QPushButton(self.page)
        self.zft_yw_hzzft_pushButton.setGeometry(QtCore.QRect(220, 190, 81, 23))
        self.zft_yw_hzzft_pushButton.setObjectName("zft_yw_hzzft_pushButton")
        self.zft_yw_tile_2_spinBox = QtWidgets.QSpinBox(self.page)
        self.zft_yw_tile_2_spinBox.setGeometry(QtCore.QRect(150, 230, 61, 22))
        self.zft_yw_tile_2_spinBox.setMaximum(999999999)
        self.zft_yw_tile_2_spinBox.setProperty("value", 8)
        self.zft_yw_tile_2_spinBox.setObjectName("zft_yw_tile_2_spinBox")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setGeometry(QtCore.QRect(20, 50, 241, 101))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 41, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(50, 70, 41, 21))
        self.label_3.setObjectName("label_3")
        self.zft_yw_start_y_spinBox = QtWidgets.QSpinBox(self.widget)
        self.zft_yw_start_y_spinBox.setGeometry(QtCore.QRect(170, 40, 61, 22))
        self.zft_yw_start_y_spinBox.setMaximum(999999999)
        self.zft_yw_start_y_spinBox.setObjectName("zft_yw_start_y_spinBox")
        self.zft_yw_start_x_spinBox = QtWidgets.QSpinBox(self.widget)
        self.zft_yw_start_x_spinBox.setGeometry(QtCore.QRect(100, 40, 61, 22))
        self.zft_yw_start_x_spinBox.setMaximum(999999999)
        self.zft_yw_start_x_spinBox.setObjectName("zft_yw_start_x_spinBox")
        self.zft_yw_end_y_spinBox = QtWidgets.QSpinBox(self.widget)
        self.zft_yw_end_y_spinBox.setGeometry(QtCore.QRect(170, 70, 61, 22))
        self.zft_yw_end_y_spinBox.setMaximum(999999999)
        self.zft_yw_end_y_spinBox.setObjectName("zft_yw_end_y_spinBox")
        self.zft_yw_end_x_spinBox = QtWidgets.QSpinBox(self.widget)
        self.zft_yw_end_x_spinBox.setGeometry(QtCore.QRect(100, 70, 61, 22))
        self.zft_yw_end_x_spinBox.setMaximum(999999999)
        self.zft_yw_end_x_spinBox.setObjectName("zft_yw_end_x_spinBox")
        self.zft_yw_checkBox = QtWidgets.QCheckBox(self.widget)
        self.zft_yw_checkBox.setGeometry(QtCore.QRect(70, 10, 71, 21))
        self.zft_yw_checkBox.setObjectName("zft_yw_checkBox")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 51, 21))
        self.label_4.setObjectName("label_4")
        self.zft_yw_range_start_spinBox = QtWidgets.QSpinBox(self.page)
        self.zft_yw_range_start_spinBox.setGeometry(QtCore.QRect(80, 190, 61, 22))
        self.zft_yw_range_start_spinBox.setMaximum(256)
        self.zft_yw_range_start_spinBox.setObjectName("zft_yw_range_start_spinBox")
        self.zft_yw_bin_spinBox = QtWidgets.QSpinBox(self.page)
        self.zft_yw_bin_spinBox.setGeometry(QtCore.QRect(80, 160, 61, 22))
        self.zft_yw_bin_spinBox.setMaximum(256)
        self.zft_yw_bin_spinBox.setProperty("value", 256)
        self.zft_yw_bin_spinBox.setObjectName("zft_yw_bin_spinBox")
        self.zft_yw_cs_checkBox = QtWidgets.QCheckBox(self.page)
        self.zft_yw_cs_checkBox.setGeometry(QtCore.QRect(190, 160, 71, 21))
        self.zft_yw_cs_checkBox.setObjectName("zft_yw_cs_checkBox")
        self.zft_yw_openfile_btn = QtWidgets.QPushButton(self.page)
        self.zft_yw_openfile_btn.setGeometry(QtCore.QRect(230, 20, 75, 23))
        self.zft_yw_openfile_btn.setObjectName("zft_yw_openfile_btn")
        self.zft_yw_limit_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.page)
        self.zft_yw_limit_doubleSpinBox.setGeometry(QtCore.QRect(80, 260, 62, 22))
        self.zft_yw_limit_doubleSpinBox.setMaximum(999999.99)
        self.zft_yw_limit_doubleSpinBox.setProperty("value", 2.0)
        self.zft_yw_limit_doubleSpinBox.setObjectName("zft_yw_limit_doubleSpinBox")
        self.zft_yw_zsyjh_pushButton = QtWidgets.QPushButton(self.page)
        self.zft_yw_zsyjh_pushButton.setGeometry(QtCore.QRect(220, 230, 81, 23))
        self.zft_yw_zsyjh_pushButton.setObjectName("zft_yw_zsyjh_pushButton")
        self.zft_yw_jhh_pushButton = QtWidgets.QPushButton(self.page)
        self.zft_yw_jhh_pushButton.setGeometry(QtCore.QRect(220, 260, 81, 23))
        self.zft_yw_jhh_pushButton.setObjectName("zft_yw_jhh_pushButton")
        self.zft_yw_range_end_spinBox = QtWidgets.QSpinBox(self.page)
        self.zft_yw_range_end_spinBox.setGeometry(QtCore.QRect(150, 190, 61, 22))
        self.zft_yw_range_end_spinBox.setMaximum(256)
        self.zft_yw_range_end_spinBox.setProperty("value", 256)
        self.zft_yw_range_end_spinBox.setObjectName("zft_yw_range_end_spinBox")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 51, 21))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 51, 21))
        self.label_5.setObjectName("label_5")
        self.zft_yw_tile_1_spinBox = QtWidgets.QSpinBox(self.page)
        self.zft_yw_tile_1_spinBox.setGeometry(QtCore.QRect(80, 230, 61, 22))
        self.zft_yw_tile_1_spinBox.setMaximum(999999999)
        self.zft_yw_tile_1_spinBox.setProperty("value", 8)
        self.zft_yw_tile_1_spinBox.setObjectName("zft_yw_tile_1_spinBox")
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setGeometry(QtCore.QRect(0, 290, 321, 311))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.widget_5 = QtWidgets.QWidget(self.frame_3)
        self.widget_5.setGeometry(QtCore.QRect(10, 10, 301, 291))
        self.widget_5.setObjectName("widget_5")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 329, 610))
        self.page_2.setObjectName("page_2")
        self.widget_4 = QtWidgets.QWidget(self.page_2)
        self.widget_4.setGeometry(QtCore.QRect(10, 30, 241, 101))
        self.widget_4.setObjectName("widget_4")
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setGeometry(QtCore.QRect(50, 40, 41, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setGeometry(QtCore.QRect(50, 70, 41, 21))
        self.label_10.setObjectName("label_10")
        self.zft_2d_start_y_spinBox = QtWidgets.QSpinBox(self.widget_4)
        self.zft_2d_start_y_spinBox.setGeometry(QtCore.QRect(170, 40, 61, 22))
        self.zft_2d_start_y_spinBox.setMaximum(999999999)
        self.zft_2d_start_y_spinBox.setObjectName("zft_2d_start_y_spinBox")
        self.zft_2d_start_x_spinBox = QtWidgets.QSpinBox(self.widget_4)
        self.zft_2d_start_x_spinBox.setGeometry(QtCore.QRect(100, 40, 61, 22))
        self.zft_2d_start_x_spinBox.setMaximum(999999999)
        self.zft_2d_start_x_spinBox.setObjectName("zft_2d_start_x_spinBox")
        self.zft_2d_end_y_spinBox = QtWidgets.QSpinBox(self.widget_4)
        self.zft_2d_end_y_spinBox.setGeometry(QtCore.QRect(170, 70, 61, 22))
        self.zft_2d_end_y_spinBox.setMaximum(999999999)
        self.zft_2d_end_y_spinBox.setObjectName("zft_2d_end_y_spinBox")
        self.zft_2d_end_x_spinBox = QtWidgets.QSpinBox(self.widget_4)
        self.zft_2d_end_x_spinBox.setGeometry(QtCore.QRect(100, 70, 61, 22))
        self.zft_2d_end_x_spinBox.setMaximum(999999999)
        self.zft_2d_end_x_spinBox.setObjectName("zft_2d_end_x_spinBox")
        self.zft_2d_checkBox = QtWidgets.QCheckBox(self.widget_4)
        self.zft_2d_checkBox.setGeometry(QtCore.QRect(70, 10, 71, 21))
        self.zft_2d_checkBox.setObjectName("zft_2d_checkBox")
        self.zft_2d_bins_start_spinBox = QtWidgets.QSpinBox(self.page_2)
        self.zft_2d_bins_start_spinBox.setGeometry(QtCore.QRect(70, 140, 61, 22))
        self.zft_2d_bins_start_spinBox.setMaximum(180)
        self.zft_2d_bins_start_spinBox.setProperty("value", 180)
        self.zft_2d_bins_start_spinBox.setObjectName("zft_2d_bins_start_spinBox")
        self.zft_2d_bins_end_spinBox = QtWidgets.QSpinBox(self.page_2)
        self.zft_2d_bins_end_spinBox.setGeometry(QtCore.QRect(140, 140, 61, 22))
        self.zft_2d_bins_end_spinBox.setMaximum(256)
        self.zft_2d_bins_end_spinBox.setProperty("value", 256)
        self.zft_2d_bins_end_spinBox.setObjectName("zft_2d_bins_end_spinBox")
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setGeometry(QtCore.QRect(10, 140, 51, 21))
        self.label_11.setObjectName("label_11")
        self.zft_2d_H0_spinBox = QtWidgets.QSpinBox(self.page_2)
        self.zft_2d_H0_spinBox.setGeometry(QtCore.QRect(70, 170, 61, 22))
        self.zft_2d_H0_spinBox.setMaximum(256)
        self.zft_2d_H0_spinBox.setObjectName("zft_2d_H0_spinBox")
        self.zft_2d_H1_spinBox = QtWidgets.QSpinBox(self.page_2)
        self.zft_2d_H1_spinBox.setGeometry(QtCore.QRect(140, 170, 61, 22))
        self.zft_2d_H1_spinBox.setMaximum(180)
        self.zft_2d_H1_spinBox.setProperty("value", 180)
        self.zft_2d_H1_spinBox.setObjectName("zft_2d_H1_spinBox")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(10, 170, 51, 21))
        self.label_12.setObjectName("label_12")
        self.zft_2d_S0_spinBox = QtWidgets.QSpinBox(self.page_2)
        self.zft_2d_S0_spinBox.setGeometry(QtCore.QRect(70, 200, 61, 22))
        self.zft_2d_S0_spinBox.setMaximum(256)
        self.zft_2d_S0_spinBox.setObjectName("zft_2d_S0_spinBox")
        self.zft_2d_S1_spinBox = QtWidgets.QSpinBox(self.page_2)
        self.zft_2d_S1_spinBox.setGeometry(QtCore.QRect(140, 200, 61, 22))
        self.zft_2d_S1_spinBox.setMaximum(256)
        self.zft_2d_S1_spinBox.setProperty("value", 256)
        self.zft_2d_S1_spinBox.setObjectName("zft_2d_S1_spinBox")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(10, 200, 51, 21))
        self.label_13.setObjectName("label_13")
        self.zft_2d_openfile_btn = QtWidgets.QPushButton(self.page_2)
        self.zft_2d_openfile_btn.setGeometry(QtCore.QRect(240, 0, 75, 23))
        self.zft_2d_openfile_btn.setObjectName("zft_2d_openfile_btn")
        self.zft_2d_OK_btn = QtWidgets.QPushButton(self.page_2)
        self.zft_2d_OK_btn.setGeometry(QtCore.QRect(210, 170, 75, 23))
        self.zft_2d_OK_btn.setObjectName("zft_2d_OK_btn")
        self.zft_2d_yszf_btn = QtWidgets.QPushButton(self.page_2)
        self.zft_2d_yszf_btn.setGeometry(QtCore.QRect(210, 200, 75, 23))
        self.zft_2d_yszf_btn.setObjectName("zft_2d_yszf_btn")
        self.frame_5 = QtWidgets.QFrame(self.page_2)
        self.frame_5.setGeometry(QtCore.QRect(0, 240, 321, 361))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.widget_8 = QtWidgets.QWidget(self.frame_5)
        self.widget_8.setGeometry(QtCore.QRect(10, 10, 301, 341))
        self.widget_8.setObjectName("widget_8")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 329, 610))
        self.page_3.setObjectName("page_3")
        self.zft_fx_openfile_btn = QtWidgets.QPushButton(self.page_3)
        self.zft_fx_openfile_btn.setGeometry(QtCore.QRect(230, 10, 75, 23))
        self.zft_fx_openfile_btn.setObjectName("zft_fx_openfile_btn")
        self.zft_fx_ok_btn = QtWidgets.QPushButton(self.page_3)
        self.zft_fx_ok_btn.setGeometry(QtCore.QRect(230, 40, 75, 23))
        self.zft_fx_ok_btn.setObjectName("zft_fx_ok_btn")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setGeometry(QtCore.QRect(20, 40, 51, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(20, 10, 51, 21))
        self.label_15.setObjectName("label_15")
        self.zft_fx_S1_spinBox = QtWidgets.QSpinBox(self.page_3)
        self.zft_fx_S1_spinBox.setGeometry(QtCore.QRect(150, 70, 61, 22))
        self.zft_fx_S1_spinBox.setMaximum(256)
        self.zft_fx_S1_spinBox.setProperty("value", 256)
        self.zft_fx_S1_spinBox.setObjectName("zft_fx_S1_spinBox")
        self.zft_fx_S0_spinBox = QtWidgets.QSpinBox(self.page_3)
        self.zft_fx_S0_spinBox.setGeometry(QtCore.QRect(80, 70, 61, 22))
        self.zft_fx_S0_spinBox.setMaximum(256)
        self.zft_fx_S0_spinBox.setObjectName("zft_fx_S0_spinBox")
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setGeometry(QtCore.QRect(20, 70, 51, 21))
        self.label_16.setObjectName("label_16")
        self.zft_fx_bins1_spinBox = QtWidgets.QSpinBox(self.page_3)
        self.zft_fx_bins1_spinBox.setGeometry(QtCore.QRect(150, 10, 61, 22))
        self.zft_fx_bins1_spinBox.setMaximum(256)
        self.zft_fx_bins1_spinBox.setProperty("value", 256)
        self.zft_fx_bins1_spinBox.setObjectName("zft_fx_bins1_spinBox")
        self.zft_fx_H0_spinBox = QtWidgets.QSpinBox(self.page_3)
        self.zft_fx_H0_spinBox.setGeometry(QtCore.QRect(80, 40, 61, 22))
        self.zft_fx_H0_spinBox.setMaximum(256)
        self.zft_fx_H0_spinBox.setObjectName("zft_fx_H0_spinBox")
        self.zft_fx_bins0_spinBox = QtWidgets.QSpinBox(self.page_3)
        self.zft_fx_bins0_spinBox.setGeometry(QtCore.QRect(80, 10, 61, 22))
        self.zft_fx_bins0_spinBox.setMaximum(180)
        self.zft_fx_bins0_spinBox.setProperty("value", 180)
        self.zft_fx_bins0_spinBox.setObjectName("zft_fx_bins0_spinBox")
        self.zft_fx_H1_spinBox = QtWidgets.QSpinBox(self.page_3)
        self.zft_fx_H1_spinBox.setGeometry(QtCore.QRect(150, 40, 61, 22))
        self.zft_fx_H1_spinBox.setMaximum(180)
        self.zft_fx_H1_spinBox.setProperty("value", 180)
        self.zft_fx_H1_spinBox.setObjectName("zft_fx_H1_spinBox")
        self.zft_fx_save_btn = QtWidgets.QPushButton(self.page_3)
        self.zft_fx_save_btn.setGeometry(QtCore.QRect(230, 70, 75, 23))
        self.zft_fx_save_btn.setObjectName("zft_fx_save_btn")
        self.frame_6 = QtWidgets.QFrame(self.page_3)
        self.frame_6.setGeometry(QtCore.QRect(0, 100, 321, 501))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.widget_9 = QtWidgets.QWidget(self.frame_6)
        self.widget_9.setGeometry(QtCore.QRect(10, 10, 301, 481))
        self.widget_9.setObjectName("widget_9")
        self.toolBox.addItem(self.page_3, "")
        self.gridLayout_3.addWidget(self.toolBox, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.widget_10)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_toolbar = QtWidgets.QWidget(self.frame_4)
        self.widget_toolbar.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_toolbar.setMaximumSize(QtCore.QSize(16777215, 41))
        self.widget_toolbar.setObjectName("widget_toolbar")
        self.gridLayout_4.addWidget(self.widget_toolbar, 0, 0, 1, 2)
        self.widget_resource_image = QtWidgets.QWidget(self.frame_4)
        self.widget_resource_image.setObjectName("widget_resource_image")
        self.gridLayout_4.addWidget(self.widget_resource_image, 1, 0, 1, 1)
        self.widget_hist_1 = QtWidgets.QWidget(self.frame_4)
        self.widget_hist_1.setObjectName("widget_hist_1")
        self.gridLayout_4.addWidget(self.widget_hist_1, 1, 1, 1, 1)
        self.widget_adaptAverage_hist = QtWidgets.QWidget(self.frame_4)
        self.widget_adaptAverage_hist.setObjectName("widget_adaptAverage_hist")
        self.gridLayout_4.addWidget(self.widget_adaptAverage_hist, 2, 1, 1, 1)
        # self.widget_adaptAverage_image.
        self.widget_adaptAverage_image = QtWidgets.QWidget(self.frame_4)
        self.widget_adaptAverage_image.setObjectName("widget_adaptAverage_image")
        self.gridLayout_4.addWidget(self.widget_adaptAverage_image, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_10, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"right\">Limit：</p></body></html>"))
        self.zft_yw_hzzft_pushButton.setText(_translate("Form", "绘制直方图"))
        self.label.setText(_translate("Form", "矩形掩模："))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"right\">起点：</p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"right\">终点：</p></body></html>"))
        self.zft_yw_checkBox.setText(_translate("Form", "True"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"right\">BIN：</p></body></html>"))
        self.zft_yw_cs_checkBox.setText(_translate("Form", "彩色图"))
        self.zft_yw_openfile_btn.setText(_translate("Form", "打开文件"))
        self.zft_yw_zsyjh_pushButton.setText(_translate("Form", "自适应均衡化"))
        self.zft_yw_jhh_pushButton.setText(_translate("Form", "均衡化"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"right\">Tile：</p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"right\">Ranges：</p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Form", "一维直方图"))
        self.label_8.setText(_translate("Form", "矩形掩模："))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"right\">起点：</p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"right\">终点：</p></body></html>"))
        self.zft_2d_checkBox.setText(_translate("Form", "True"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p align=\"right\">Bins：</p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"right\">H_Ranges：</p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"right\">S_Ranges：</p></body></html>"))
        self.zft_2d_openfile_btn.setText(_translate("Form", "打开文件"))
        self.zft_2d_OK_btn.setText(_translate("Form", "确定"))
        self.zft_2d_yszf_btn.setText(_translate("Form", "颜色直方图"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Form", "2D直方图"))
        self.zft_fx_openfile_btn.setText(_translate("Form", "打开文件"))
        self.zft_fx_ok_btn.setText(_translate("Form", "确定"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p align=\"right\">H_Ranges：</p></body></html>"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p align=\"right\">Bins：</p></body></html>"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p align=\"right\">S_Ranges：</p></body></html>"))
        self.zft_fx_save_btn.setText(_translate("Form", "保存"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Form", "反向投影"))
